apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cloud-controller-manager-vpa
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: {{ include "deploymentversion" . }}
    kind: Deployment
    name: cloud-controller-manager
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: gcp-cloud-controller-manager
      minAllowed:
        cpu: {{ .Values.resources.requests.cpu }}
        memory: {{ .Values.resources.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.resources.maxAllowed.cpu }}
        memory: {{ .Values.resources.maxAllowed.memory }}
      controlledValues: RequestsOnly
