replicas: 1
podAnnotations: {}

images:
  csi-driver: image-repository:image-tag
  csi-provisioner: image-repository:image-tag
  csi-attacher: image-repository:image-tag
  csi-snapshotter: image-repository:image-tag
  csi-resizer: image-repository:image-tag
  csi-liveness-probe: image-repository:image-tag
  csi-snapshot-controller: image-repository:image-tag
  csi-snapshot-validation-webhook: image-repository:image-tag

socketPath: /var/lib/csi/sockets/pluginproxy
projectID: foo
zone: bar

resources:
  driver:
    requests:
      cpu: 20m
      memory: 50Mi
    limits:
      memory: 210Mi
    maxAllowed:
      cpu: 800m
      memory: 4G
  provisioner:
    requests:
      cpu: 11m
      memory: 32Mi
    limits:
      memory: 200Mi
    maxAllowed:
      cpu: 800m
      memory: 4G
  attacher:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      memory: 210Mi
    maxAllowed:
      cpu: 500m
      memory: 4G
  snapshotter:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 256Mi
    maxAllowed:
      cpu: 700m
      memory: 4G
  resizer:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 200Mi
    maxAllowed:
      cpu: 700m
      memory: 2G
  livenessProbe:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 110Mi
    maxAllowed:
      cpu: 500m
      memory: 2G

csiSnapshotController:
  replicas: 1
  podAnnotations: {}
  resources:
    requests:
      cpu: 11m
      memory: 32Mi
    limits:
      memory: 2.2Gi

csiSnapshotValidationWebhook:
  replica: 1
  podAnnotations: {}
  secrets:
    server: csi-snapshot-validation-server
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 200Mi
